//app/layout.js
'use client'
import useVendorNotifications from "@/app/hooks/useVendorNotifications";
import SidePanel from "@/components/sidepanel/SidePanel";
import { ThemeProvider } from "@/components/theme/theme-provider";
import { Poppins } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.css";
import "react-quill-new/dist/quill.snow.css";

const poppins = Poppins({
  subsets: ['latin'], // Supports Latin characters
  weight: ['300', '400', '500', '600', '700'], // Choose weights you need
  style: ['normal', 'italic'], // Optional: Include styles
  variable: '--font-poppins' // Creates a CSS variable
});

const metadata = {
  title: "Yoyda admin panel",
  description: "Generated by create next app",
};

export default function RootLayout({children}) {
  useVendorNotifications();
  return (
    <html lang="en" className={poppins.variable}>
      <head>
        <link rel="icon" href="/logo/logo.png" type="image/png"  />
        <title>Yoyda</title>
      </head>
      <body suppressHydrationWarning={true}>
        <ThemeProvider attribute="class" defaultTheme="light" enableSystem={true} disableTransitionOnChange>
          <SidePanel>{children}</SidePanel>
        </ThemeProvider>
        <Toaster/>
      </body>
    </html>
  );
}
